name: Deploy frontend

on: workflow_dispatch

env:
  CI: false # disable treating warnings as errors on CI

jobs:
  build-and-deploy:
    name: Build & deploy frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & deploy service
        uses: ./.github/actions/build-and-deploy-node
        with:
          service-name: frontend
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          ssh-key: ${{ secrets.SSH_KEY }}
          restart: false
